name: video_compress_plus
description: Light library of video manipulation of Flutter. Compress video, remove audio, get video thumbnail from dart code.
version: 1.0.0
homepage: https://github.com/kamaravichow/VideoCompressPlus

environment:
  sdk: '>=2.16.2 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.aravi.video_compress
        pluginClass: VideoCompressPlugin
      ios:
        pluginClass: VideoCompressPlugin
      macos:
        pluginClass: VideoCompressPlugin

  